spring:
  application:
    name: licensing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI}"

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
