spring:
  application:
    name: licensing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI}"

resilience4j:
  ratelimiter:
    instances:
      licenseService:
        timeoutDuration: 1000
        limitRefreshPeriod: 5000
        limitForPeriod: 5


logging:
  level:
    com:
      optimagrowth: debug
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
    root: info
